{% set name = "fps-auth-base" %}
{% set version = "0.0.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth_base-{{ version }}.tar.gz
  sha256: d3c754ec74f1c7867037a29550aef176b5f7d01033202512094fad9878c8315c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - fps >=0.0.17,<1

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_base
  summary: An FPS plugin for the authentication API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_base
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
